# Para conectarse a mongodb desde MongoDBCompass, usar esta string:
# mongodb://usuario:contraseña@localhost:27018/
#
# Es necesario crear un fichero .env e introducir estas variables dentro:
# MONGO_INITDB_DATABASE=nombre de la base de datos
# MONGO_INITDB_ROOT_USERNAME=usuario administrador de la BD
# MONGO_INITDB_ROOT_PASSWORD=contraseña de ese usuario
# MONGO_URL=url que usará JS para conectarse
#
version: "3"
services:
  api:
    build: ./nodejs
    hostname: node_api
    container_name: node_api
    restart: always
    env_file: .env
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - backend
  mongo:
    image: mongo:latest
    hostname: mongo_database
    container_name: mongo_database
    restart: always
    env_file: .env
    volumes:
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "27018:27017"
    networks:
      - backend
networks:
  backend:
